### ISSUE TITLE
Possibility to fit complex models

### ISSUE THREAD

**Issue by stanleyrazor** [inlabru-org/dirinla#1]
Thank you for providing this package!

I wanted to inquire if the package in its current state can fit temporal (ar/rw) and spatial models (spde).
I would appreciate a simple dummy example.

Let me know if this is not the appropriate forum for raising this question, and I will oblige.

Thanks.

**Comment by finnlindgren** [comment]
No, in its current state only fixed effects and iid effects are implemented. We've just started working on a possible extension to allow essentially any latent model, but that work has just started. I think Joaquin may have some other code for inla that uses a different approximation, that maybe handles more models.

**Comment by stanleyrazor** [comment]
Thanks for the response.

**Comment by jmartinez-minaya** [comment]
Hi!

For fitting CoDa models with temporal or spatial random effects you could
use INLAcomp (https://jmartinez-minaya.github.io/INLAcomp/). It uses
another approximation but also with the Dirichlet structure.
link for the paper:
https://link.springer.com/article/10.1007/s11222-024-10427-3

Soon, the spatio-temporal option will be available also for dirinla.

Best regards,
Joaquín.
